### PR TITLE
add some resnet.py docstring

### PR DESCRIPTION
**Pull request by SuX97**
- add some resnet.py docstring to reach 100% coverage
- revise some docstring by docformatter

### CODE REVIEW

**Comment by innerlee** [comment]
Could you investigate the linting error in CI?

**Comment by innerlee** [comment]
Might be caused by isort version

**Comment by SuX97** [comment]
> Might be caused by isort version

Yes, older version of isort is good while version >5.x.x will discover new linting errors.

**Comment by innerlee** [comment]
image

sth went wrong?

**Comment by SuX97** [comment]
> image
> 
> sth went wrong?

No, all are done by the new isort.

**Comment by innerlee** [comment]
okay make the ci pass then

**Comment by innerlee** [comment]
how about sticking to the old isort

**Comment by innerlee** [comment]
could you fix this branch and rebase master?

**Pull request closed without merging**
